spring:
  profiles:
    active: local

logging:
  level:
    ROOT: info

data:
  firebase:
    path: "./src/main/resources/firebase-account-info.json"
    collections:
      reservation:
        name: "reservations"

server:
  port: 8080
  servlet:
    context-path: "/api"
    