spring:
  profiles:
    active: local

logging:
  level:
    ROOT: info

reservations:
  firebase:
    path: "./firebase-account-info.json"

server:
  port: 8080
  servlet:
    context-path: "/api"
    