spring:
  profiles:
    active: local

logging:
  level:
    ROOT: info

data:
  firebase:
    path: "./src/main/resources/firebase-account-info.json"
    collections:
      reservation:
        name: "reservations"

server:
  port: 8080
  servlet:
    context-path: "/api"

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "*"
      path-mapping:
        metrics: "metric-names"
        prometheus: "metrics"
  prometheus:
    metrics:
      export:
        enabled: true